# from tkinter import *
# root=Tk()
# mymenu=Menu(root)
# root.config(menu=mymenu)
# submenu=Menu(mymenu)
# mymenu.add_cascade(label="file",menu=submenu)
# submenu.add_command(label='New File')
# submenu.add_command(label='Open File')
# submenu.add_command(label='Open Folder')
# submenu.add_separator()
# submenu.add_command(label='save')
# newmenu=Menu(mymenu)
# mymenu.add_cascade(label="Edit",menu=newmenu)
# newmenu.add_command(label='Undo')
# newmenu.add_command(label='Redo')
# newmenu.add_separator()
# newmenu.add_command(label='Cut')
# newmenu.add_command(label='Copy')
# newmenu.add_command(label='Paste')
# root.mainloop()



from tkinter import *
root=Tk()
mymenu=Menu(root)
root.config(menu=mymenu)
submenu=Menu(mymenu)
mymenu.add_cascade(label="File",menu=submenu)
submenu.add_command(label='New File')
submenu.add_command(label='Open File')
submenu.add_command(label='Open Folder')
submenu.add_separator()
submenu.add_command(label='save')
submenu1=Menu(mymenu)
mymenu.add_cascade(label="View",menu=submenu1)
submenu1.add_command(label='Command palette')
submenu1.add_command(label='Open View')
submenu1.add_separator()
submenu1.add_command(label='Appearance')
submenu1.add_command(label='Editor Layout')
submenu1.add_separator()
submenu1.add_command(label='Explorer')
root.mainloop()