
from tkinter import *
root=Tk()
mymenu=Menu(root)
root.config(menu=mymenu)
submenu=Menu(mymenu)
mymenu.add_cascade(label="File",menu=submenu)
submenu.add_command(label='New File')
submenu.add_command(label='Open File')
submenu.add_command(label='Open Folder')
submenu.add_separator()
submenu.add_command(label='save')
submenu1=Menu(mymenu)
mymenu.add_cascade(label="View",menu=submenu1)
submenu1.add_command(label='Command palette')
submenu1.add_command(label='Open View')
submenu1.add_separator()
submenu1.add_command(label='Appearance')
submenu1.add_command(label='Editor Layout')
submenu1.add_separator()
submenu1.add_command(label='Explorer')
submenu2=Menu(mymenu)
mymenu.add_cascade(label="Edit",menu=submenu2)
submenu2.add_command(label='Undo')
submenu2.add_command(label='Redo')
submenu2.add_separator()
submenu2.add_command(label='Cut')
submenu2.add_command(label='Copy')
submenu2.add_command(label='Paste')
submenu3=Menu(mymenu)
mymenu.add_cascade(label="Selection",menu=submenu3)
submenu3.add_command(label='Selectall')
submenu3.add_command(label='Expand Selection')
submenu3.add_command(label='Shrink Selection')
submenu3.add_separator()
submenu3.add_command(label='Copy Line Up')
submenu3.add_command(label='Copy Line Down')
submenu1.add_command(label='Move Line Up')

"""TOOLBRANDSTATUSBAR"""

toolbar=Frame(root,bg='red')
btn1=Button(toolbar,text='crop')
btn1.pack(side=TOP,padx=5,pady=5)
toolbar.pack(fill='x',side=TOP)
statusbar=Label(root,text='This is status bar',anchor=N,bg='blue',fg='white')
statusbar.pack(fill='x',side=BOTTOM)
root.mainloop()